name: dart_practice
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Shudipto <Shudiptotrafder@gmail.com>

environment:
  sdk: '>=2.1.0-dev.9.4 <3.0.0'

dependencies:
  path: ^1.6.2
  archive:  ^2.0.7
  pointycastle: ^1.0.0
  sqljocky5: ^2.2.0
  http: ^0.12.0+1

dev_dependencies:
  #test: ^1.5.2
